# Generated by Django 4.0.4 on 2022-05-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('zone', models.IntegerField(default=1)),
                ('pop', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('total_mac', models.IntegerField()),
                ('smart_link', models.BooleanField(default=False)),
                ('sep', models.BooleanField(default=False)),
                ('stack', models.BooleanField(default=False)),
                ('number_of_pop_tail', models.IntegerField()),
                ('patch_ver', models.CharField(max_length=100)),
                ('patch_state', models.CharField(max_length=100)),
                ('software_ver', models.CharField(max_length=100)),
                ('switch_type', models.CharField(max_length=100)),
            ],
        ),
    ]
