# Generated by Django 4.0.4 on 2022-05-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='_id',
        ),
        migrations.AlterField(
            model_name='content',
            name='branch',
            field=models.CharField(default='BTHT1', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='function',
            field=models.CharField(default='SW-FTI-BB', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='hostname',
            field=models.CharField(default='HNIB03405HW50', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='ip',
            field=models.CharField(default='10.41.2.28', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='model',
            field=models.CharField(default='HW50', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='patch_state',
            field=models.CharField(default='Running', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='patch_ver',
            field=models.CharField(default='s5720si-v200r011sph007', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='pop',
            field=models.CharField(default='HNIB034', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='province',
            field=models.CharField(default='HNI', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='software_ver',
            field=models.CharField(default='S5720 V200R011C10SPC600', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='switch_type',
            field=models.CharField(default='S5720-28X', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(default='HUAWEI', max_length=100),
        ),
    ]
